FROM golang:1.23-alpine

# Set the working directory to /app/services/users
WORKDIR /app/services/users

# Install Air for live reloading
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum /app/

RUN cd /app && go mod download

# Copy the rest of the application code to /app
COPY . /app

# Expose port if necessary
EXPOSE 8000

# Start the application with Air
CMD ["air", "-c", "config/.air.toml"]

