FROM golang:1.23-alpine

WORKDIR /app/services/user

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum /app/

RUN cd /app && go mod download

COPY . /app

EXPOSE 8000

CMD ["air", "-c", "config/.air.toml"]

