FROM golang:1.23-alpine

# Set the working directory to /app/services/users
WORKDIR /app/services/users

# Install Air for live reloading
RUN go install github.com/air-verse/air@latest

# Copy go.mod and go.sum to /app
COPY go.mod go.sum /app/

# Copy the services/users/go.mod and go.sum to /app/services/users if they exist
# If not, skip this step

# Download dependencies
RUN cd /app && go mod download

# Copy the rest of the application code to /app
COPY . /app

# Expose port if necessary
EXPOSE 1234

# Start the application with Air
CMD ["air", "-c", "config/.air.toml"]

