// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                int32
	Username          string
	Email             string
	PasswordHash      string
	FirstName         pgtype.Text
	LastName          pgtype.Text
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
	IsActive          pgtype.Bool
	IsAdmin           pgtype.Bool
	LastLogin         pgtype.Timestamp
	ProfilePictureUrl pgtype.Text
	Bio               pgtype.Text
	DateOfBirth       pgtype.Date
	PhoneNumber       pgtype.Text
	Address           []byte
}
