// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"context"
)

type Querier interface {
	// Insert a new user into the users table
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Delete a user by their ID
	DeleteUser(ctx context.Context, id int32) error
	// Fetch a single user by their ID
	GetUserByID(ctx context.Context, id int32) (User, error)
	// Fetch a single user by their username
	GetUserByUsername(ctx context.Context, username string) (User, error)
	// Fetch a paginated list of users from the table
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// Update the active status of a user
	SetUserActiveStatus(ctx context.Context, arg SetUserActiveStatusParams) error
	// Update the last login timestamp for a user
	UpdateLastLogin(ctx context.Context, id int32) error
	// Update a user's information
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
